### ISSUE TITLE
SocketException at the very end of training at clients

### ISSUE THREAD

**Issue by thangnbn** [bnnthang/FederatedLearningTestbed#20]
Clients show SocketException at the end of training. Perhaps this is because the server closes the connections right after sending the DONE command.

```
java.net.SocketException: Socket is closed
     at java.net.Socket.getInputStream(Socket.java:960)
     at com.bnnthang.fltestbed.commonutils.clients.BaseClient.serve(BaseClient.java:74)
     at com.bnnthang.fltestbed.commonutils.clients.BaseClient.run(BaseClient.java:55)
     at com.bnnthang.fltestbed.androidclient.ClientThread.run(ClientThread.java:46)
```

**Comment by thangnbn** [comment]
Close for now because we cannot reproduce the issue. We might open this again in the future when someone can show a reliable way to reproduce this issue.
